"""init schema

Revision ID: 7bbe47984efa
Revises: 
Create Date: 2026-05-07 00:41:40.536733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bbe47984efa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label', sa.SmallInteger(), nullable=False),
    sa.Column('probability', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('predictions_created_at_idx', 'predictions', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_table('promotion_events',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('promoted_version', sa.Integer(), nullable=False),
    sa.Column('previous_version', sa.Integer(), nullable=True),
    sa.Column('investigation_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hil_approvals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('investigation_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('index_trace_request_metadata_request_id', table_name='trace_request_metadata')
    op.drop_table('trace_request_metadata')
    op.drop_index('index_trace_tags_request_id', table_name='trace_tags')
    op.drop_table('trace_tags')
    op.drop_index('index_inputs_destination_type_destination_id_source_type', table_name='inputs')
    op.drop_index('index_inputs_input_uuid', table_name='inputs')
    op.drop_table('inputs')
    op.drop_table('experiments')
    op.drop_index('index_latest_metrics_run_uuid', table_name='latest_metrics')
    op.drop_table('latest_metrics')
    op.drop_table('model_version_tags')
    op.drop_index('index_trace_info_experiment_id_timestamp_ms', table_name='trace_info')
    op.drop_table('trace_info')
    op.drop_table('registered_models')
    op.drop_index('index_metrics_run_uuid', table_name='metrics')
    op.drop_table('metrics')
    op.drop_table('input_tags')
    op.drop_index('index_datasets_dataset_uuid', table_name='datasets')
    op.drop_index('index_datasets_experiment_id_dataset_source_type', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('index_params_run_uuid', table_name='params')
    op.drop_table('params')
    op.drop_table('registered_model_aliases')
    op.drop_table('model_versions')
    op.drop_table('registered_model_tags')
    op.drop_table('runs')
    op.drop_table('experiment_tags')
    op.drop_index('index_tags_run_uuid', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name='tags_run_uuid_fkey'),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name='tag_pk')
    )
    op.create_index('index_tags_run_uuid', 'tags', ['run_uuid'], unique=False)
    op.create_table('experiment_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name='experiment_tags_experiment_id_fkey'),
    sa.PrimaryKeyConstraint('key', 'experiment_id', name='experiment_tag_pk')
    )
    op.create_table('runs',
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('entry_point_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('source_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lifecycle_stage', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('artifact_uri', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("lifecycle_stage::text = ANY (ARRAY['active'::character varying, 'deleted'::character varying]::text[])", name='runs_lifecycle_stage'),
    sa.CheckConstraint("source_type::text = ANY (ARRAY['NOTEBOOK'::character varying, 'JOB'::character varying, 'LOCAL'::character varying, 'UNKNOWN'::character varying, 'PROJECT'::character varying]::text[])", name='source_type'),
    sa.CheckConstraint("status::text = ANY (ARRAY['SCHEDULED'::character varying, 'FAILED'::character varying, 'FINISHED'::character varying, 'RUNNING'::character varying, 'KILLED'::character varying]::text[])", name='runs_status_check'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name='runs_experiment_id_fkey'),
    sa.PrimaryKeyConstraint('run_uuid', name='run_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_table('registered_model_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name'], ['registered_models.name'], name='registered_model_tags_name_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'name', name='registered_model_tag_pk')
    )
    op.create_table('model_versions',
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('current_stage', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('run_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('run_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('storage_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['name'], ['registered_models.name'], name='model_versions_name_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('name', 'version', name='model_version_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_table('registered_model_aliases',
    sa.Column('alias', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name'], ['registered_models.name'], name='registered_model_alias_name_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name', 'alias', name='registered_model_alias_pk')
    )
    op.create_table('params',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name='params_run_uuid_fkey'),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name='param_pk')
    )
    op.create_index('index_params_run_uuid', 'params', ['run_uuid'], unique=False)
    op.create_table('datasets',
    sa.Column('dataset_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('digest', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('dataset_source_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('dataset_source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dataset_schema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dataset_profile', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name='fk_datasets_experiment_id_experiments', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experiment_id', 'name', 'digest', name='dataset_pk')
    )
    op.create_index('index_datasets_experiment_id_dataset_source_type', 'datasets', ['experiment_id', 'dataset_source_type'], unique=False)
    op.create_index('index_datasets_dataset_uuid', 'datasets', ['dataset_uuid'], unique=False)
    op.create_table('input_tags',
    sa.Column('input_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('input_uuid', 'name', name='input_tags_pk')
    )
    op.create_table('metrics',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('step', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False),
    sa.Column('is_nan', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name='metrics_run_uuid_fkey'),
    sa.PrimaryKeyConstraint('key', 'timestamp', 'step', 'run_uuid', 'value', 'is_nan', name='metric_pk')
    )
    op.create_index('index_metrics_run_uuid', 'metrics', ['run_uuid'], unique=False)
    op.create_table('registered_models',
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='registered_model_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_table('trace_info',
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('execution_time_ms', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name='fk_trace_info_experiment_id'),
    sa.PrimaryKeyConstraint('request_id', name='trace_info_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_index('index_trace_info_experiment_id_timestamp_ms', 'trace_info', ['experiment_id', 'timestamp_ms'], unique=False)
    op.create_table('model_version_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name', 'version'], ['model_versions.name', 'model_versions.version'], name='model_version_tags_name_version_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'name', 'version', name='model_version_tag_pk')
    )
    op.create_table('latest_metrics',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('step', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_nan', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name='latest_metrics_run_uuid_fkey'),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name='latest_metric_pk')
    )
    op.create_index('index_latest_metrics_run_uuid', 'latest_metrics', ['run_uuid'], unique=False)
    op.create_table('experiments',
    sa.Column('experiment_id', sa.INTEGER(), server_default=sa.text("nextval('experiments_experiment_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('artifact_location', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('lifecycle_stage', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("lifecycle_stage::text = ANY (ARRAY['active'::character varying, 'deleted'::character varying]::text[])", name='experiments_lifecycle_stage'),
    sa.PrimaryKeyConstraint('experiment_id', name='experiment_pk'),
    sa.UniqueConstraint('name', name='experiments_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('inputs',
    sa.Column('input_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('destination_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('destination_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('source_type', 'source_id', 'destination_type', 'destination_id', name='inputs_pk')
    )
    op.create_index('index_inputs_input_uuid', 'inputs', ['input_uuid'], unique=False)
    op.create_index('index_inputs_destination_type_destination_id_source_type', 'inputs', ['destination_type', 'destination_id', 'source_type'], unique=False)
    op.create_table('trace_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['trace_info.request_id'], name='fk_trace_tags_request_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'request_id', name='trace_tag_pk')
    )
    op.create_index('index_trace_tags_request_id', 'trace_tags', ['request_id'], unique=False)
    op.create_table('trace_request_metadata',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['trace_info.request_id'], name='fk_trace_request_metadata_request_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'request_id', name='trace_request_metadata_pk')
    )
    op.create_index('index_trace_request_metadata_request_id', 'trace_request_metadata', ['request_id'], unique=False)
    op.drop_table('hil_approvals')
    op.drop_table('promotion_events')
    op.drop_index('predictions_created_at_idx', table_name='predictions', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('predictions')
    op.drop_table('investigations')
    # ### end Alembic commands ###
