"""init schema

Revision ID: b8b18f902dcf
Revises: 
Create Date: 2026-05-07 01:33:13.482617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8b18f902dcf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label', sa.SmallInteger(), nullable=False),
    sa.Column('probability', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('predictions_created_at_idx', 'predictions', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_table('promotion_events',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('promoted_version', sa.Integer(), nullable=False),
    sa.Column('previous_version', sa.Integer(), nullable=True),
    sa.Column('investigation_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hil_approvals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('investigation_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hil_approvals')
    op.drop_table('promotion_events')
    op.drop_index('predictions_created_at_idx', table_name='predictions', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('predictions')
    op.drop_table('investigations')
    # ### end Alembic commands ###
